services:

  flask_app:
    container_name: flask_app
    image: nabeelaccount/fask-api-sqlalchemy:latest
    build: .  # Build image on current directory
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@flask_db:5432/postgres    # env variable required by application
    depends_on:
      - flask_db
      
  flask_db:
    container_name: flask_db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:  # Create persistant application
      - pgdata:/var/lib/postgresql/data   # local:remote

volumes:
  pgdata: {}
    